# Generated by Django 2.0.6 on 2018-06-26 01:44

import bfat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0010_alliance_ticker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bfat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualFat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCharacter')),
                ('creator', models.ForeignKey(on_delete=models.SET(bfat.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('fatlink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bfat.FatLink')),
            ],
        ),
    ]
